import type { Metadata } from 'next'
import { useSite } from "@/hooks/use-site"

export const metadata: Metadata = {
    title: 'Privacy Policy',
}

export default function PrivacyPolicyPage() {
    const { site } = useSite()
    const domain = site.host

    return (
        <main className="max-w-4xl mx-auto px-4 py-12">
            <article className="prose prose-neutral max-w-none">
                <h1>Privacy Policy</h1>

                <p>
                    This Privacy Policy describes Our policies and procedures on the
                    collection, use and disclosure of Your information when You use the
                    Service and tells You about Your privacy rights and how the law
                    protects You.
                </p>

                <p>
                    We use Your Personal data to provide and improve the Service. By
                    using the Service, You agree to the collection and use of information
                    in accordance with this Privacy Policy.
                </p>

                <h2>Interpretation and Definitions</h2>

                <h3>Interpretation</h3>

                <p>
                    The words of which the initial letter is capitalized have meanings
                    defined under the following conditions. The following definitions
                    shall have the same meaning regardless of whether they appear in
                    singular or in plural.
                </p>

                <h3>Definitions</h3>

                <p>For the purposes of this Privacy Policy:</p>

                <ul>
                    <li>
                        <strong>Account</strong> means a unique account created for You to
                        access our Service or parts of our Service.
                    </li>

                    <li>
                        <strong>Affiliate</strong> means an entity that controls, is
                        controlled by or is under common control with a party.
                    </li>

                    <li>
                        <strong>Company</strong> (referred to as either “the Company”, “We”,
                        “Us” or “Our” in this Agreement) refers to The Daily Sports.
                    </li>

                    <li>
                        <strong>Cookies</strong> are small files that are placed on Your
                        computer, mobile device or any other device by a website.
                    </li>

                    <li>
                        <strong>Country</strong> refers to: New York, United States.
                    </li>

                    <li>
                        <strong>Device</strong> means any device that can access the Service
                        such as a computer, a cellphone or a digital tablet.
                    </li>

                    <li>
                        <strong>Personal Data</strong> is any information that relates to an
                        identified or identifiable individual.
                    </li>

                    <li>
                        <strong>Service</strong> refers to the Website.
                    </li>

                    <li>
                        <strong>Service Provider</strong> means any natural or legal person
                        who processes the data on behalf of the Company.
                    </li>

                    <li>
                        <strong>Usage Data</strong> refers to data collected automatically,
                        either generated by the use of the Service or from the Service
                        infrastructure itself.
                    </li>

                    <li>
                        <strong>Website</strong> refers to The Daily Sports accessible from{" "}
                        <a
                            href={`https://${domain}`}
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            https://{domain}
                        </a>
                    </li>

                    <li>
                        <strong>You</strong> means the individual accessing or using the
                        Service.
                    </li>
                </ul>

                <h2>Collecting and Using Your Personal Data</h2>

                <h3>Types of Data Collected</h3>

                <h4>Personal Data</h4>

                <p>
                    While using Our Service, We may ask You to provide Us with certain
                    personally identifiable information that can be used to contact or
                    identify You.
                </p>

                <h4>Usage Data</h4>

                <p>Usage Data is collected automatically when using the Service.</p>

                <p>
                    Usage Data may include information such as Your Device’s Internet
                    Protocol address (e.g. IP address), browser type, browser version,
                    pages visited, time and date of visits, time spent on pages, unique
                    device identifiers and other diagnostic data.
                </p>

                <p>
                    When You access the Service through a mobile device, We may collect
                    additional information automatically.
                </p>

                <h2>Tracking Technologies and Cookies</h2>

                <p>
                    We use Cookies and similar tracking technologies to track activity on
                    Our Service and store certain information.
                </p>

                <ul>
                    <li>
                        <strong>Cookies or Browser Cookies.</strong> A cookie is a small
                        file placed on Your Device.
                    </li>

                    <li>
                        <strong>Web Beacons.</strong> Certain sections of our Service and
                        emails may contain small electronic files known as web beacons.
                    </li>
                </ul>

                <p>
                    Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies
                    remain on Your device when offline, while Session Cookies are deleted
                    once You close Your browser.
                </p>

                <h3>Types of Cookies We Use</h3>

                <ul>
                    <li>
                        <strong>Necessary / Essential Cookies</strong>
                        <p>Type: Session Cookies</p>
                        <p>Administered by: Us</p>
                        <p>
                            Purpose: Essential for providing services and authentication.
                        </p>
                    </li>

                    <li>
                        <strong>Cookies Policy / Notice Acceptance Cookies</strong>
                        <p>Type: Persistent Cookies</p>
                        <p>Administered by: Us</p>
                        <p>
                            Purpose: Identifies whether users have accepted cookies.
                        </p>
                    </li>

                    <li>
                        <strong>Functionality Cookies</strong>
                        <p>Type: Persistent Cookies</p>
                        <p>Administered by: Us</p>
                        <p>
                            Purpose: Remembers preferences such as login details and language.
                        </p>
                    </li>
                </ul>

                <h2>Use of Your Personal Data</h2>

                <p>The Company may use Personal Data for the following purposes:</p>

                <ul>
                    <li>To provide and maintain our Service.</li>
                    <li>To manage Your Account.</li>
                    <li>For the performance of a contract.</li>
                    <li>To contact You.</li>
                    <li>To provide news, offers and updates.</li>
                    <li>To manage Your requests.</li>
                    <li>For business transfers.</li>
                    <li>
                        For analytics, improving services and marketing effectiveness.
                    </li>
                </ul>

                <h2>Sharing Your Personal Information</h2>

                <p>
                    We may share Your personal information in the following situations:
                </p>

                <ul>
                    <li>With Service Providers.</li>
                    <li>For business transfers.</li>
                    <li>With Affiliates.</li>
                    <li>With business partners.</li>
                    <li>With other users.</li>
                    <li>With Your consent.</li>
                </ul>

                <h2>Retention of Your Personal Data</h2>

                <p>
                    The Company will retain Your Personal Data only for as long as
                    necessary for the purposes set out in this Privacy Policy.
                </p>

                <h2>Transfer of Your Personal Data</h2>

                <p>
                    Your information may be transferred to and maintained on computers
                    located outside of Your jurisdiction where data protection laws may
                    differ.
                </p>

                <h2>Delete Your Personal Data</h2>

                <p>
                    You have the right to delete or request assistance in deleting Your
                    Personal Data.
                </p>

                <h2>Disclosure of Your Personal Data</h2>

                <h3>Business Transactions</h3>

                <p>
                    If the Company is involved in a merger, acquisition or asset sale,
                    Your Personal Data may be transferred.
                </p>

                <h3>Law Enforcement</h3>

                <p>
                    The Company may disclose Your Personal Data if required by law or in
                    response to valid requests by public authorities.
                </p>

                <h3>Other Legal Requirements</h3>

                <ul>
                    <li>Comply with legal obligations.</li>
                    <li>Protect Company rights or property.</li>
                    <li>Prevent wrongdoing.</li>
                    <li>Protect user safety.</li>
                    <li>Protect against legal liability.</li>
                </ul>

                <h2>Security of Your Personal Data</h2>

                <p>
                    While We strive to use commercially acceptable means to protect Your
                    Personal Data, no method of transmission or storage is 100% secure.
                </p>

                <h2>Children’s Privacy</h2>

                <p>
                    Our Service does not address anyone under the age of 13.
                </p>

                <h2>Links to Other Websites</h2>

                <p>
                    Our Service may contain links to third-party websites not operated by
                    Us.
                </p>

                <h2>Changes to this Privacy Policy</h2>

                <p>
                    We may update Our Privacy Policy from time to time. Changes become
                    effective once posted on this page.
                </p>

                <h2>Contact Us</h2>

                <p>
                    If you have any questions about this Privacy Policy, You can contact
                    us:
                </p>

                <ul>
                    <li>
                        By email:{" "}
                        <a href={`mailto:support@${domain}`}>
                            support@{domain}
                        </a>
                    </li>
                </ul>
            </article>
        </main>
    );
}