import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { ThemeProvider } from "@/providers/theme.provider"
import { siteService } from "@/services/site.service"
import { Suspense } from "react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function SiteBoundary({ children }: Readonly<{ children: React.ReactNode }>) {
  const site = await siteService.getCurrentSite()

  return <ThemeProvider site={site}>{children}</ThemeProvider>
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Suspense fallback={<div />}>
          <SiteBoundary>{children}</SiteBoundary>
        </Suspense>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
